version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: chessDRA2021
      MYSQL_USER: user
      MYSQL_PASSWORD: chessDRA21
      MYSQL_DATABASE: chessDB
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

  adminer:
      depends_on:
        - db
      image: adminer
      restart: unless-stopped
      ports:
        - 8080:8080

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "/etc/timezone:/etc/timezone:ro"
<<<<<<< HEAD:docker-compose.yml
          - "mosquitto-config:/opt/mosquitto/config"
          - "mosquitto-data:/opt/mosquitto/data"
          - "mosquitto-log:/opt/mosquitto/log"

=======
          - "./mosquitto-config:/mosquitto/config"
          - "./mosquitto-data:/mosquitto/data"
          - "./mosquitto-log:/mosquitto/log"

  rails:
    image: jps105/rvm
    depends_on:
      - db
    links:
      - "db:database"
    volumes:
      - ../Oauth2Server:/usr/src
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    command: bash -l -c "cd /usr/src && bundle install && rails db:create && rails db:migrate && rails s -b 0.0.0.0 -p 3000"
  
>>>>>>> 2d55950e424deb06acdf48b07d10e4442b719b2d:backend/infrastructure/docker-compose.yml
volumes:
  db_data: